// Command notices generates THIRD-PARTY-NOTICES.txt from the module cache.
//
// It resolves the set of packages actually linked into the given patterns
// (default ./...), then collects every license and notice file that
// applies to them: the ones at each dependency module's root, plus any found
// in the directory chain between an imported package and its module root.
// Sub-packages we do not import contribute nothing, which keeps the file to
// the licenses we are genuinely bound by.
//
// Apache-2.0 section 4 requires redistributing NOTICE files with binary
// distributions, so the generated file ships in the release archives.
//
// NOT TESTED: this package has no unit tests and is excluded from the coverage
// profile by COVER_PKGS in the Makefile. It is a build-time generator: it never
// ships in the binary, and its only output is THIRD-PARTY-NOTICES.txt, which
// `make notices-check` regenerates and compares on every build and in CI. That
// catches a regression; it does not catch a licence this never collected in the
// first place. See docs/coverage-gaps.md, "The notices generator".
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const header = `THIRD-PARTY NOTICES

This file is generated by "make notices". Do not edit it by hand.

tun-manager is distributed under the BSD 3-Clause License (see LICENSE). It
links the third-party modules listed below, each under its own terms. The
full text of every applicable license and notice file is reproduced verbatim.

`

// listedPackage is the subset of "go list -json" output that we need.
type listedPackage struct {
	ImportPath string `json:"ImportPath"`
	Dir        string `json:"Dir"`
	Standard   bool   `json:"Standard"`
	Module     *struct {
		Path    string `json:"Path"`
		Version string `json:"Version"`
		Dir     string `json:"Dir"`
		Main    bool   `json:"Main"`
	} `json:"Module"`
}

// moduleLicenses accumulates the license files that apply to one module.
type moduleLicenses struct {
	path    string
	version string
	files   map[string]string // relative path within the module -> absolute path
}

func main() {
	out := flag.String("o", "THIRD-PARTY-NOTICES.txt", "output file, or - for stdout")
	flag.Parse()

	patterns := flag.Args()
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}

	rendered, err := generate(context.Background(), patterns)
	if err != nil {
		fmt.Fprintf(os.Stderr, "notices: %v\n", err)
		os.Exit(1)
	}

	if *out == "-" {
		fmt.Print(rendered)
		return
	}
	if err := os.WriteFile(*out, []byte(rendered), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "notices: %v\n", err)
		os.Exit(1)
	}
}

func generate(ctx context.Context, patterns []string) (string, error) {
	pkgs, err := listPackages(ctx, patterns)
	if err != nil {
		return "", err
	}

	mods := map[string]*moduleLicenses{}
	for _, pkg := range pkgs {
		if pkg.Standard || pkg.Module == nil || pkg.Module.Main || pkg.Module.Dir == "" {
			continue
		}
		mod, ok := mods[pkg.Module.Path]
		if !ok {
			mod = &moduleLicenses{
				path:    pkg.Module.Path,
				version: pkg.Module.Version,
				files:   map[string]string{},
			}
			mods[pkg.Module.Path] = mod
			collectInto(mod, pkg.Module.Dir, pkg.Module.Dir)
		}
		// Walk from the imported package up to the module root so that
		// vendored sub-licenses (for example klauspost/compress's zstd
		// xxhash) are picked up, without pulling in sub-packages we never
		// import.
		for dir := pkg.Dir; strings.HasPrefix(dir, pkg.Module.Dir); dir = filepath.Dir(dir) {
			collectInto(mod, dir, pkg.Module.Dir)
			if dir == pkg.Module.Dir {
				break
			}
		}
	}

	if len(mods) == 0 {
		return header + "tun-manager currently has no third-party dependencies.\n", nil
	}

	paths := make([]string, 0, len(mods))
	for path := range mods {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("Modules:\n\n")
	for _, path := range paths {
		fmt.Fprintf(&b, "  - %s %s\n", path, mods[path].version)
	}

	for _, path := range paths {
		mod := mods[path]
		rels := make([]string, 0, len(mod.files))
		for rel := range mod.files {
			rels = append(rels, rel)
		}
		sort.Strings(rels)

		for _, rel := range rels {
			content, err := os.ReadFile(mod.files[rel])
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "\n%s\n%s %s -- %s\n%s\n\n", strings.Repeat("=", 78),
				mod.path, mod.version, rel, strings.Repeat("=", 78))
			b.Write(content)
			if len(content) > 0 && content[len(content)-1] != '\n' {
				b.WriteByte('\n')
			}
		}
	}
	return b.String(), nil
}

// collectInto records the license files sitting directly in dir.
func collectInto(mod *moduleLicenses, dir, moduleRoot string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if entry.IsDir() || !isLicenseFile(entry.Name()) {
			continue
		}
		abs := filepath.Join(dir, entry.Name())
		rel, err := filepath.Rel(moduleRoot, abs)
		if err != nil {
			continue
		}
		mod.files[filepath.ToSlash(rel)] = abs
	}
}

func isLicenseFile(name string) bool {
	upper := strings.ToUpper(name)
	for _, prefix := range []string{"LICENSE", "LICENCE", "COPYING", "NOTICE"} {
		if strings.HasPrefix(upper, prefix) {
			return true
		}
	}
	return false
}

// targets are the platforms the release binaries are built for.
//
// go list resolves build constraints for one platform at a time, so the answer
// depends on the machine running it. Listing every shipped target and merging
// keeps the file from omitting a license one of the binaries is bound by.
var targets = []struct{ goos, goarch string }{
	{"darwin", "amd64"},
	{"darwin", "arm64"},
}

// listPackages returns the union of the dependencies of every target platform,
// deduplicated by import path and in a deterministic order.
func listPackages(ctx context.Context, patterns []string) ([]listedPackage, error) {
	var (
		all  []listedPackage
		seen = map[string]bool{}
	)
	for _, target := range targets {
		pkgs, err := listPackagesFor(ctx, target.goos, target.goarch, patterns)
		if err != nil {
			return nil, fmt.Errorf("%s/%s: %w", target.goos, target.goarch, err)
		}
		for _, pkg := range pkgs {
			if pkg.ImportPath != "" && seen[pkg.ImportPath] {
				continue
			}
			seen[pkg.ImportPath] = true
			all = append(all, pkg)
		}
	}
	return all, nil
}

func listPackagesFor(ctx context.Context, goos, goarch string, patterns []string) ([]listedPackage, error) {
	args := append([]string{"list", "-deps", "-json"}, patterns...)
	cmd := exec.CommandContext(ctx, "go", args...)
	cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch)
	cmd.Stderr = os.Stderr
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	if err := cmd.Start(); err != nil {
		return nil, err
	}

	var pkgs []listedPackage
	dec := json.NewDecoder(stdout)
	for {
		var pkg listedPackage
		if err := dec.Decode(&pkg); err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			_ = cmd.Wait()
			return nil, err
		}
		pkgs = append(pkgs, pkg)
	}
	if err := cmd.Wait(); err != nil {
		return nil, fmt.Errorf("go list: %w", err)
	}
	return pkgs, nil
}
